### ISSUE TITLE
Missing osc-bsu-csi-driver chart asset

### ISSUE THREAD

**Issue by fheslouin** [outscale/osc-bsu-csi-driver#623]
I'm looking for an archive of osc-bsu-csi-driver chart to download, the last version did not produce any assets. For a comparison cloud-provider-osc assets is made available for each release https://github.com/outscale/cloud-provider-osc/releases/tag/v0.2.0

It would be very helpful to have such assets

**Comment by outscale-mdr** [comment]
Hello @fheslouin,

Currently, we provide two different ways to install the CSI:
- [ArtifactHub](https://artifacthub.io/packages/search?repo=osc-bsu-csi-driver)
- Helm using the plugin [helm-git](https://github.com/aslafy-z/helm-git).

We can if these methods do not satisfy your needs, upload the package in the release.

Best regards,
Maxime

**Comment by outscale-mdr** [comment]
Yes good point, we had the same issue for the CCM. This is why the chart was included in the last CCM release.

I will upload the artefact for this release (v1.1.1)  today and for the next releases, we will automate the upload process.

**Comment by fheslouin** [comment]
Great ! thanks a lot
