### ISSUE TITLE
Support extra environment variables in the Chart (e.g. for HTTP Proxy)

### ISSUE THREAD

**Issue by outscale-age** [outscale/osc-bsu-csi-driver#636]
**Is your feature request related to a problem? Please describe.**

I would like to use osc-bsu-csi-driver behind an HTTP proxy. A possible way to do this is to pass environment variables like `https_proxy` to the BSU CSI Driver containers. However, this is not supported today, and forces me to work around by patching the Chart.

**Describe the solution you'd like in detail**

Two enhancements could be done:

- A generic way of overriding environment variables on the BSU CSI Driver (see `extraEnv` suggestion below).
- Documenting the required environment variables to run the BSU CSI Driver behind a Proxy (https_proxy, no_proxy).

**Additional context**

Helm charts typically have knobs like `extraEnv` in the `values.yaml` to set static extra environment variables in the Deployments, StatefulSets, etc.

Some variables could contain secrets, and therefore often an `extraSecretEnv` is also offered, which manages a dedicated secret and its presentation.

Example overrides in a chart: https://github.com/hashicorp/vault-helm/blob/main/values.yaml#L511

**Comment by outscale-vbr** [comment]
@outscale-age 
 HTTP Proxy is now included in osc-bsu-csi charts

**Comment by outscale-hmi** [comment]
https://github.com/outscale/osc-bsu-csi-driver/pull/810
