### ISSUE TITLE
xfs as fstype: missing xfs_growfs in $PATH

### ISSUE THREAD

**Issue by albundy83** [outscale/osc-bsu-csi-driver#774]
/kind bug

**What happened?**
It seems that when we use xfs as `fstype`, `allowVolumeExpansion` could not work as in Docker image, we don't have the `xfs_growfs` binary.

I encounter this error:
```
MountVolume.Setup failed while expanding volume for volume "pvc-xxxxxxxxxxxxxxxxx" : Expander.NodeExpand failed to expand the volume : rpc error: code = Internal desc = Could not resize volume "vol-xxxxxxxx" ("/dev/xvdf"): resize of device /var/lib/kubelet/pods/xxxxxxxxxxxxx/volumes/kubernetes.io~csi/pvc-xxxxxxxxxxxxxxxxx/mount failed: executable file not found in $PATH. xfs_growfs output:
```

Checking the Docker file here https://github.com/outscale/osc-bsu-csi-driver/blob/v1.2.3/Dockerfile#L26 and according to Alpine pkg, you need also `xfsprogs-extra` to be able to use `xfs_growfs` https://alpine.pkgs.org/3.16/alpine-main-x86_64/xfsprogs-extra-5.16.0-r1.apk.html

Maybe you could also update Alpine release while you are here :-) https://github.com/outscale/osc-bsu-csi-driver/blob/v1.2.3/Dockerfile#L22

**Environment**
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.7", GitCommit:"84e1fc493a47446df2e155e70fca768d2653a398", GitTreeState:"clean", BuildDate:"2023-07-19T12:23:27Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.7+rke2r1", GitCommit:"84e1fc493a47446df2e155e70fca768d2653a398", GitTreeState:"clean", BuildDate:"2023-07-19T20:19:16Z", GoVersion:"go1.20.6 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version: 
v1.2.3

Thanks a lot for your help

**Comment by outscale-vbr** [comment]
@albundy83 
A new release v1.2.4 is released which has included xfs_growfs package in dockerfile.

**Comment by albundy83** [comment]
Just try the v1.2.4 release and my PVC has grown perfectly :)
Thanks a lot
