### ISSUE TITLE
Unable to create IO1 storage from our Openshift management console

### ISSUE THREAD

**Issue by jordanyoumbinumspot** [outscale/osc-bsu-csi-driver#784]
Hello,
we can not create IO1 type of storage from our Openshift cluster. we have followed your template to write our yaml file. here is our yaml:

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: slow
provisioner: bsu.csi.outscale.com
parameters:
type: io1
iopsPerGB: "10"
fsType: ext4

and here is the error we are receiving:

I0912 12:49:52.488384 1 connection.go:187] GRPC error: rpc error: code = Internal desc = Could not create volume "pvc-36278801-f9a4-436c-a36a-a54f298ccc3a": could not create volume in Outscale: 400 Bad Request

9473I0912 12:49:52.488419 1 controller.go:767] CreateVolume failed, supports topology = true, node selected false => may reschedule = false => state = Finished: rpc error: code = Internal desc = Could not create volume "pvc-36278801-f9a4-436c-a36a-a54f298ccc3a": could not create volume in Outscale: 400 Bad Request

9474I0912 12:49:52.488452 1 controller.go:1074] Final error received, removing PVC 36278801-f9a4-436c-a36a-a54f298ccc3a from claims in progress

9475W0912 12:49:52.488461 1 controller.go:933] Retrying syncing claim "36278801-f9a4-436c-a36a-a54f298ccc3a", failure 3

9476E0912 12:49:52.488475 1 controller.go:956] error syncing claim "36278801-f9a4-436c-a36a-a54f298ccc3a": failed to provision volume with StorageClass "outscale-bsu-io1": rpc error: code = Internal desc = Could not create volume "pvc-36278801-f9a4-436c-a36a-a54f298ccc3a": could not create volume in Outscale: 400 Bad Request

9477I0912 12:49:52.488495 1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kube-system", Name:"test", UID:"36278801-f9a4-436c-a36a-a54f298ccc3a", APIVersion:"v1", ResourceVersion:"424882", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "outscale-bsu-io1": rpc error: code = Internal desc = Could not create volume "pvc-36278801-f9a4-436c-a36a-a54f298ccc3a": could not create volume in Outscale: 400 Bad Request

9478I0912 12:49:52.488673 1 request.go:1181] Request Body: {"count":4,"lastTimestamp":"2023-09-12T12:49:52Z","message":"failed to provision volume with StorageClass \"outscale-bsu-io1\": rpc error: code = Internal desc = Could not create volume \"pvc-36278801-f9a4-436c-a36a-a54f298ccc3a\": could not create volume in Outscale: 400 Bad Request"}

9479I0912 12:49:52.488746 1 round_trippers.go:435] curl -v -XPATCH -H "Accept: application/json, */*" -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: csi-provisioner/v0.0.0 (linux/amd64) kubernetes/$Format" -H "Authorization: Bearer <masked>" '[https://172.30.0.1:443/api/v1/namespaces/kube-system/events/test.178427ad569f843a'<https://172.30.0.1/api/v1/namespaces/kube-system/events/test.178427ad569f843a%27](https://172.30.0.1/api/v1/namespaces/kube-system/events/test.178427ad569f843a'%3Chttps://172.30.0.1/api/v1/namespaces/kube-system/events/test.178427ad569f843a%27)>

9480I0912 12:49:52.496620 1 round_trippers.go:454] PATCH [https://172.30.0.1:443/api/v1/namespaces/kube-system/events/test.178427ad569f843a<https://172.30.0.1/api/v1/namespaces/kube-system/events/test.178427ad569f843a](https://172.30.0.1/api/v1/namespaces/kube-system/events/test.178427ad569f843a%3Chttps://172.30.0.1/api/v1/namespaces/kube-system/events/test.178427ad569f843a)> 200 OK in 7 milliseconds

Erreur Interface graphique :
[cid:5b6909bb-cb85-4156-aa57-8cd6f1080292]

Please can you help us find what is the problem ? i am ready to take a call whenever you want.

Sincerely,
Jordan

**Comment by outscale-vbr** [comment]
Hi @jordanyoumbinumspot 
Can you please send us the logs of the csi controller to see which call are getting 400 error (It is even better with request_id) ?

**Comment by jordanyoumbinumspot** [comment]
Hello vincent,

For the moment i only have the logs i have sent you. it is impossible to check with these logs ?

**Comment by outscale-vbr** [comment]
Hi, 
It is impossible to check only with the current logs.
Can you get logs from csi controller ?

kubectl logs -f   bsu-csi-controller-xxxx  -n kube-system  -c bsu-plugin  

Can you also send you pvc configuration ?
Can you test to create a volume with the same characteristic with osc-cli or cockpit ?

**Comment by davmartini** [comment]
Hi,

More information bellow :

**Storage Class :**

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: outscale-bsu-io1
provisioner: bsu.csi.outscale.com
parameters:
  csi.storage.k8s.io/fstype: ext4
  iopsPerGB: '100'
  type: io1
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**PVC :**

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test
  namespace: kube-system
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: bsu.csi.outscale.com
    volume.kubernetes.io/storage-provisioner: bsu.csi.outscale.com
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: outscale-bsu-io1
  volumeMode: Block
status:
  phase: Pending
```

**Pods related to CSI restart too many time :** 

```
bash-4.4 ~ $ oc get pods
NAME                                 READY   STATUS    RESTARTS          AGE
osc-csi-controller-967f6fcfb-7fp6r   6/6     Running   553 (25m ago)     2d15h
osc-csi-controller-967f6fcfb-dljnr   6/6     Running   507 (7m9s ago)    2d15h
osc-csi-node-2sqwq                   3/3     Running   3                 4d18h
osc-csi-node-49kf5                   2/3     Error     740 (5m16s ago)   4d18h
osc-csi-node-5cz9g                   3/3     Running   3                 4d18h
osc-csi-node-dn52k                   3/3     Running   3                 4d18h
osc-csi-node-rshn2                   3/3     Running   3                 4d18h
osc-csi-node-xmzgz                   3/3     Running   3                 4d18h
```

** osc-plugin logs from CSI controller :**

```
I0918 07:54:11.730738 1 identity.go:62] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0918 07:54:17.034689 1 identity.go:62] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0918 07:54:21.730907 1 identity.go:62] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0918 07:54:27.035275 1 identity.go:62] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0918 07:54:31.731077 1 identity.go:62] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0918 07:54:37.035359 1 identity.go:62] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0918 07:54:41.731092 1 identity.go:62] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0918 07:54:47.035244 1 identity.go:62] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0918 07:54:51.731141 1 identity.go:62] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0918 07:54:57.035325 1 identity.go:62] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0918 07:55:01.730753 1 identity.go:62] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0918 07:55:07.035120 1 identity.go:62] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0918 07:55:11.730466 1 identity.go:62] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0918 07:55:17.035777 1 identity.go:62] Probe: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
```

**error logs on CSI controller pod during PVC provisioning :**

```
{"Errors":[{"Type":"InvalidParameterValue","Details":"","Code":"4078"}],"ResponseContext":{"RequestId":"08f9cb61-6e25-4194-85b2-84928b131817"}}
I0918 08:23:54.847903       1 cloud.go:370] Debug response CreateVolume: response({ResponseContext:<nil> Volume:<nil>}), err(400 Bad Request), httpRes(&{400 Bad Request 400 HTTP/1.1 1 1 map[Access-Control-Allow-Origin:[*] Connection:[keep-alive] Content-Length:[143] Content-Type:[application/json] Date:[Mon, 18 Sep 2023 08:23:54 GMT] Server:[nginx]] {{"Errors":[{"Type":"InvalidParameterValue","Details":"","Code":"4078"}],"ResponseContext":{"RequestId":"08f9cb61-6e25-4194-85b2-84928b131817"}}} 143 [] false false map[] 0xc000671300 0xc000632bb0})
400 Bad Request
```

**Comment by outscale-vbr** [comment]
Hello @jordanyoumbinumspot @davmartini 

The minimum size of a io1 is [4Gb](https://docs.outscale.com/api#createvolume), could you test with at least 4Gb please ?

Best regards,
Vincent

**Comment by davmartini** [comment]
Hello,

It's works with 10Go requested. Where this information is documented? I saw anything about this prerequisite. Can you help us about the fact than csi pods restart many times?

**Comment by jerome-jutteau** [comment]
Hi @davmartini 

Yes, check [Volumes documentation](https://docs.outscale.com/en/userguide/About-Volumes.html):
> Volume size
> 4 GiB - 14.55 TiB (14901 GiB)
