### ISSUE TITLE
access to our created OMI on cockpit v1

### ISSUE THREAD

**Issue by jordanyoumbinumspot** [outscale/osc-bsu-csi-driver#785]
Hello,

We would like to know if it is possible for us to have access to our created OMI on cockpit v1. We have access through cockpit v2 but it is unpleasant to switch our interface often to see our OMI.

Sincerely,
Jordan

**Comment by outscale-vbr** [comment]
Hi @jordanyoumbinumspot ,
Sorry, this is the wrong place for this question. You should contact outscale support (https://fr.outscale.com/support-technique/).
