### ISSUE TITLE
Lien privé vers le CSI driver

### ISSUE THREAD

**Issue by jordanyoumbinumspot** [outscale/osc-bsu-csi-driver#788]
hello,

We are creating storage class (IO1, GP2 and standard) from our Openshift cluster. 

Unfortunately, right now we are only able to create it through public endpoint.

Can you provide us a private endpoint that achieves the creation of those storages class  without going to internet ?  

Sincerely,
Jordan

**Comment by jerome-jutteau** [comment]
Hi @jordanyoumbinumspot,

You will have to create a [VPC Endpoint / Net Access Point](https://docs.outscale.com/fr/userguide/%C3%80-propos-des-Net-access-points.html), test it and configure CSI to use it.

We are preparing a more detailed response to show you how to do this.

**Comment by outscale-vbr** [comment]
Hello @jordanyoumbinumspot ,

After testing in our dev cluster, you just need to create a VPC Endpoint in the public Subnet and the CSI will be able to  make calls to the API without going through an Internet Gateway.

Best regards, 
Vincent

**Comment by jordanyoumbinumspot** [comment]
Hello,

Please when do you think we can have the detailed documentation about this implementation ?

Sincerely,
Jordan

**Comment by jerome-jutteau** [comment]
Hi

Steps are pretty straightforward:

1. I suppose you don't have any Internet Gateway left (at least no route to it)
2. [Create a net access point](https://docs.outscale.com/api?console#createnetaccesspoint) with netId the id of your vpc, routeTableId the routeTable associated with your public subnet.
3. You request to Outscale API should now be routed through the net access point. Nothing left to do.

**Comment by jordanyoumbinumspot** [comment]
hello jerome

it is not working for us.

here is our context:
we have 2 private subnets (not connected to internet gateway) and 2 public subnets connected to internet gateway.

we want to connect to the CSI driver only from the private subnets. so we don't understand your second step (routeTableId the routeTable associated with your public subnet). 

Please can you provide us a solution that works for us  ?

Sincerely,
Jordan

**Comment by jerome-jutteau** [comment]
> Hi,

You first need to have a working VPC Endpoint.

You can try connecting through ssh on the node running the CSI and test your VPC Endpoint using curl > v7.75:

```bash
export OSC_REGION=eu-west-2
export OSC_ACCESS_KEY=YYY
export OSC_SECRET_KEY=ZZZ
curl https://api.$OSC_REGION.outscale.com/api/v1/ReadVolumes --user $OSC_ACCESS_KEY:$OSC_SECRET_KEY --aws-sigv4 'osc' --header 'Content-Type: application/json' --data '{}' 
```

Once this command is working properly, we will be able to study any CSI-related issue here.

For issues regarding VPC Endpoint itself, you would need to contact Outscale's support team or your Technical Account Manager as it is out of the scope of this project and would require much more details to share which may stay private.

**Comment by jordanyoumbinumspot** [comment]
it is working. thank you
