### ISSUE TITLE
Our openshift pod can't find PVC previously mounted when it restarts

### ISSUE THREAD

**Issue by jyoumbi-numspot** [outscale/osc-bsu-csi-driver#791]
[**What]([url](url)) happened?**

When a pod restarts, it has difficulty to find the PVC that is previously attached to him.

**What you expected to happen?**

We expect the pod to easily attach to the PVC volume that was create through the CSI driver

**How to reproduce it (as minimally and precisely as possible)?**

delete de pod and watch him trying to connect to the pvc and fail multiple time.

**Environment**
- Openshift: 4.13.5
- Driver version:
<img width="1484" alt="MicrosoftTeams-image (1)" src="https://github.com/outscale/osc-bsu-csi-driver/assets/145103981/97705b61-f5bd-4a54-a1ec-76bcc3bd5c53">

**Comment by outscale-vbr** [comment]
Hi @jordanyoumbinumspot,
Can you please send us the logs of the csi controller and the csi node  ?
Can you also send us the PersistantVolumeClaim and StorageClass yaml manifest ? 
Best Regards,
Vincent Baer
