### ISSUE TITLE
Unable to create a PVC with less than 4 Gb

### ISSUE THREAD

**Issue by jordanyoumbinumspot** [outscale/osc-bsu-csi-driver#792]
Hello,

we need less than 4gb for our pod. how can we do it ?

Today, we are limited to create at least 4GB of storage. 

**What happened?**

We can not create a PVC for our pod that is less than 4 GB

**What you expected to happen?**

The creation of pod with 1gb as PVC

**How to reproduce it (as minimally and precisely as possible)?**

Try our PVC yaml script:

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test
  namespace: kube-system
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: bsu.csi.outscale.com
    volume.kubernetes.io/storage-provisioner: bsu.csi.outscale.com
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: outscale-bsu-io1
  volumeMode: Block

**Environment**
- OPenshift: 4.13.5

**Comment by outscale-mdr** [comment]
Hello @jordanyoumbinumspot,

In Outscale cloud, io1 volume size cannot be smaller than 4Gb. In the [documentation](https://docs.outscale.com/en/userguide/About-Volumes.html#_volume_types_and_iops), you can see the   specification of different volume types. If you need a smaller disk, try to use `gp2` disks, but be careful you cannot set iops for this type of volumes.

Can you confirm us that you try to create io1 volumes ? You can have the information in the `Storage Class` definition, here the Storage Class name is `outscale-bsu-io1`.

Best regards,
Maxime Dufour

**Comment by jordanyoumbinumspot** [comment]
hello,

yes it is the IO1 that we are trying to create. we have already created the GP2 with 1gb and it is working well

so, is there a possibility to create IO1 with less than 4gb ? it is important for our architecture in Openshift 

Sincerely,
Jordan

**Comment by outscale-mdr** [comment]
Hello @jordanyoumbinumspot,

With the current state of Outscale IaaS, this is not possible for io1 volumes. Please contact the support for more details.
