### ISSUE TITLE
Support kubernetes 1.27 and/or update compatibility matrix

### ISSUE THREAD

**Issue by pierreozoux** [outscale/osc-bsu-csi-driver#802]
Hi,

1.26 is almost EOL:
https://kubernetes.io/releases/

I think it'd be nice to update code and/or [CSI Specification Compability Matrix](https://github.com/outscale/osc-bsu-csi-driver?tab=readme-ov-file#csi-specification-compability-matrix)

We are currently running 1.27.

Thanks for your work!

**Comment by outscale-hmi** [comment]
Now We are supporting k8s 1.30
