### ISSUE TITLE
Add the ability to use cross namespace volume data sources

### ISSUE THREAD

**Issue by yacinebbt** [outscale/osc-bsu-csi-driver#809]
**What happened?**

following the official documentation of kubernetes, and in order to be able to use cross namespace volume data sources, i have to activate _**CrossNamespaceVolumeDataSource**_  feature gate for the csi-provisioner.

i quote from their doc (https://kubernetes.io/docs/concepts/storage/persistent-volumes/#cross-namespace-data-sources):

"
_**Also, you must enable the CrossNamespaceVolumeDataSource feature gate for the csi-provisioner.
Enabling the CrossNamespaceVolumeDataSource feature gate allows you to specify a namespace in the dataSourceRef field.**_
" 
and here is the example how it works (https://kubernetes.io/docs/concepts/storage/persistent-volumes/#using-a-cross-namespace-volume-data-source).

My problem is that i don't know how can i enable this feature in the osc-bsu-csi driver. if you can help, i'll be very grateful.

**What you expected to happen?**
The ability to use this feature.

**How to reproduce it (as minimally and precisely as possible)?**
follow the official documentation, but before that, you are forced to enable this feature in osc-bsu-csi-driver because it's a prerequisite.

**Environment**
- Kubernetes version (v1.27.12+rke2r1):
- Driver version: osc-bsu-csi-driver-1.4.0

Thank you for your help

**Comment by jerome-jutteau** [comment]
Hi, you should be able to enable features through [csi-provisionner's side car parameters](https://github.com/outscale/osc-bsu-csi-driver/blob/03ef2e643fe560e1ec0c36fd5d5622cb9897c2cb/osc-bsu-csi-driver/templates/controller.yaml#L135) but I think this could also be a Chart option to add.
cc @outscale-hmi

**Comment by yacinebbt** [comment]
Hello @jerome-jutteau,

Thank you for your fast reply, i'll test that and I'll keep you informed.

**Comment by jerome-jutteau** [comment]
It seems csi-provisioner sidecar [v3.0.0](https://github.com/kubernetes-csi/external-provisioner/tree/v3.0.0) does not support this feature but [v3.4.0](https://github.com/kubernetes-csi/external-provisioner/tree/v3.4.0) has CrossNamespaceVolumeDataSource feature.
@outscale-hmi, maybe we can even upgrade further and use the latest version (currently [v4.0.1](https://github.com/kubernetes-csi/external-provisioner/tree/v4.0.1).

**Comment by yacinebbt** [comment]
Thank you for your help, i tried both of them (v3.4.0 and v4.0.1) and both of them support it

```
W0514 15:10:11.130928       1 feature_gate.go:241] Setting GA feature gate Topology=true. It will be removed in a future release.
I0514 15:10:11.131028       1 feature_gate.go:249] feature gates: &{map[CrossNamespaceVolumeDataSource:true Topology:true]}
I0514 15:10:11.131068       1 csi-provisioner.go:154] Version: v4.0.1
I0514 15:10:11.131082       1 csi-provisioner.go:177] Building kube configs for running in cluster...
I0514 15:10:11.131707       1 connection.go:215] Connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
I0514 15:10:11.132873       1 common.go:138] Probing CSI driver for readiness
I0514 15:10:11.132906       1 connection.go:244] GRPC call: /csi.v1.Identity/Probe
I0514 15:10:11.132910       1 connection.go:245] GRPC request: {}
I0514 15:10:11.135242       1 connection.go:251] GRPC response: {}
I0514 15:10:11.135316       1 connection.go:252] GRPC error: <nil>
I0514 15:10:11.135377       1 connection.go:244] GRPC call: /csi.v1.Identity/GetPluginInfo
I0514 15:10:11.135401       1 connection.go:245] GRPC request: {}
I0514 15:10:11.136384       1 connection.go:251] GRPC response: {"name":"bsu.csi.outscale.com","vendor_version":"v1.3.0"}
I0514 15:10:11.136420       1 connection.go:252] GRPC error: <nil>
I0514 15:10:11.136443       1 csi-provisioner.go:230] Detected CSI driver bsu.csi.outscale.com
I0514 15:10:11.136465       1 connection.go:244] GRPC call: /csi.v1.Identity/GetPluginCapabilities
I0514 15:10:11.136476       1 connection.go:245] GRPC request: {}
I0514 15:10:11.137495       1 connection.go:251] GRPC response: {"capabilities":[{"Type":{"Service":{"type":1}}},{"Type":{"Service":{"type":2}}}]}
I0514 15:10:11.137544       1 connection.go:252] GRPC error: <nil>
I0514 15:10:11.137574       1 connection.go:244] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I0514 15:10:11.137592       1 connection.go:245] GRPC request: {}
```

```
W0514 15:11:05.678994       1 feature_gate.go:241] Setting GA feature gate Topology=true. It will be removed in a future release.
I0514 15:11:05.679110       1 feature_gate.go:249] feature gates: &{map[CrossNamespaceVolumeDataSource:true Topology:true]}
I0514 15:11:05.679152       1 csi-provisioner.go:154] Version: v3.4.0
I0514 15:11:05.679195       1 csi-provisioner.go:177] Building kube configs for running in cluster...
I0514 15:11:05.679704       1 connection.go:154] Connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
I0514 15:11:05.680499       1 common.go:111] Probing CSI driver for readiness
I0514 15:11:05.680654       1 connection.go:183] GRPC call: /csi.v1.Identity/Probe
I0514 15:11:05.680663       1 connection.go:184] GRPC request: {}
I0514 15:11:05.684044       1 connection.go:186] GRPC response: {}
I0514 15:11:05.684083       1 connection.go:187] GRPC error: <nil>
I0514 15:11:05.684090       1 connection.go:183] GRPC call: /csi.v1.Identity/GetPluginInfo
I0514 15:11:05.684093       1 connection.go:184] GRPC request: {}
I0514 15:11:05.684524       1 connection.go:186] GRPC response: {"name":"bsu.csi.outscale.com","vendor_version":"v1.3.0"}
I0514 15:11:05.684553       1 connection.go:187] GRPC error: <nil>
I0514 15:11:05.684560       1 csi-provisioner.go:230] Detected CSI driver bsu.csi.outscale.com
I0514 15:11:05.684566       1 connection.go:183] GRPC call: /csi.v1.Identity/GetPluginCapabilities
I0514 15:11:05.684568       1 connection.go:184] GRPC request: {}
I0514 15:11:05.685082       1 connection.go:186] GRPC response: {"capabilities":[{"Type":{"Service":{"type":1}}},{"Type":{"Service":{"type":2}}}]}
I0514 15:11:05.685163       1 connection.go:187] GRPC error: <nil>
I0514 15:11:05.685170       1 connection.go:183] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I0514 15:11:05.685173       1 connection.go:184] GRPC request: {}
```
So i can say that all releases starting from v3.4.0 support this feature.

I will try to produce the same result as the kubernetes cross namespace volume data sources and then close the issue.

Thank you for your help again :).
Regards

**Comment by outscale-hmi** [comment]
Hello, 
External provisioner is now upgraded to v5.0.2
