### ISSUE TITLE
Remove default value for imagePullSecrets

### ISSUE THREAD

**Issue by albundy83** [outscale/osc-bsu-csi-driver#811]
/kind bug
Hello,

can you remove the default value for the imagePullSecrets which are here:
https://github.com/outscale/osc-bsu-csi-driver/blob/master/osc-bsu-csi-driver/templates/node.yaml#L44
and here:
https://github.com/outscale/osc-bsu-csi-driver/blob/master/osc-bsu-csi-driver/templates/controller.yaml#L47

As if we don't use it, we have Events complaining about missing Secret.

Thanks a lot :)

**Comment by albundy83** [comment]
Hello,

here the repeating message from Kubernetes Events "Unable to retrieve some image pull secrets (registry-dockerconfigjson); attempting to pull the image may not succeed."

**Comment by outscale-hmi** [comment]
https://github.com/outscale/osc-bsu-csi-driver/pull/815 merged
